app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key= True)
    username = db.Column(db.String(255),nullable=False, unique=True)
    email = db.Column(db.String(255), nullable =False,unique=True)
    bio = db.Column(db.String(255))
    profile_img = db.Column(db.String(255))
    password_u = db.Column(db.String(255),nullable = False)
    pitches = db.relationship('Pitch', backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment', backref = 'user', lazy = 'dynamic')
    def save_user(self):
        db.session.add(self)
        db.session.commit()
    def delete_user(self):
        db.session.delete(self)
        db.session.commit()
    @property
    def password(self):
        raise AttributeError('You cannot read the password atrribute')
   
    @password.setter
    def password(self, password):
        self.password_u = generate_password_hash(password)
   
    def verify_password(self, password):
        return check_password_hash(self.password_u, password)
    def __repr__(self):
     return f'User {self.username}'
class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(40))
    content = db.Column(db.String)
    category = db.Column(db.String(40))
    author = db.Column(db.String(40))
    upvote = db.Column(db.Integer)
    downvote = db.Column(db.Integer)
    date_posted = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref = 'pitch', lazy = 'dynamic')
    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    content = db.Column(db.String)
    date_posted = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    @login_manager.user_loader
        
    def load_user(user_id):
        return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, RadioField
from wtforms.validators import DataRequired
class Pitch_Form(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    content = TextAreaField('Write Pitch', validators=[DataRequired()])
    category = RadioField('Pick Category', choices=[('Pickup Lines', 'Pickup Lines'), ('Interview Pitch', 'Interview Pitch'), ('Product Pitch', 'Product Pitch'), ('Promotion Pitch', 'Promotion Pitch')], validators=[DataRequired()])
    submit = SubmitField('Submit')
class Update_Profile(FlaskForm):
    bio = TextAreaField('Add something more about Yourself...', validators = [DataRequired()])
    submit = SubmitField('Submit')
class CommentsForm(FlaskForm):
    comment = TextAreaField('comment on the post',validators=[DataRequired()])
    submit = SubmitField('Add Comment')
    

app/__init__.py
from flask import Flask
from config import Config
import os
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

app = Flask(__name__)
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
def pitch_app(config_name):
    
    app.config.from_object(config_options[config_name])
    # initialize extensions
    login_manager.init_app(app)
    db.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
   # configure UploadSet
    configure_uploads(app,photos)
   # registering main blueprint
   
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    # registering auth blueprint
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main' ,__name__)
from .import views

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from flask_login import login_required,current_user
from ..models import User,Pitch,Comment
from .forms import Pitch_Form, Update_Profile,CommentsForm
from .. import db ,photos
@main.route('/')
def index():
    """
    View root page function that returns the index page and its data
    """
    return render_template('index.html')
@main.route('/all_pitches')
def all_pitches():
    general = Pitch.query.all()
    return render_template('all_pitches.html',general=general)
@main.route('/interview')
def interview():
    comment = Comment.query.all()
    interview= Pitch.query.filter_by(category = 'Interview Pitch').all()
    return render_template('interview.html',interview=interview,comment=comment)
@main.route('/promotion')
def promotion():
    comment = Comment.query.all()
    promotion = Pitch.query.filter_by(category = 'Promotion Pitch').all()
    return render_template('promotion.html',promotion=promotion,comment=comment)
@main.route('/product')
def product():
    comment = Comment.query.all()
    product = Pitch.query.filter_by(category = 'Product Pitch').all()
    return render_template('product.html',product=product,comment=comment)
@main.route('/pickup')
def pickup():
    comment = Comment.query.all()
    pickup = Pitch.query.filter_by(category = 'Pickup Lines').all()
    return render_template('pickup.html', pickup=pickup,comment=comment)
@main.route('/new_pitch', methods = ['GET','POST'])
@login_required
def new_pitch():
    form = Pitch_Form()
    if form.validate_on_submit():
        pitch = Pitch(title = form.title.data, category =form.category.data, content = form.content.data, author = form.author.data,upvote = 0,downvote = 0,user_id=current_user.id)
        pitch.save_pitch()
        return redirect(url_for('main.all_pitches'))
    return render_template('new_pitch.html', pitch_form = form)
@main.route('/<username>')
@login_required
def profile(username):
    pitch = Pitch.query.filter_by(user_id= current_user.id).all()
    user = User.query.filter_by(username = username).first()
    return render_template('profile.html', user = user, pitch = pitch)
@main.route('/<username>/update/pic', methods = ['POST'])
@login_required
def update_profile_pic(username):
    user = User.query.filter_by(username = username).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_img = path
        db.session.commit()
    return redirect(url_for('main.profile', username = username))
@main.route('/user/<username>/update',methods = ['GET','POST'])
@login_required
def update_profile(username):
    user = User.query.filter_by(username = username).first()
    if user is None:
        abort(404)
        form = Update_Profile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.profile',username=user.username))
    return render_template('update_profile.html',form =form)
@main.route('/comments/<int:pitch_id>/comment',methods=['POST','GET'])
@login_required
def comment(pitch_id):
    form = CommentsForm()
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    user = current_user.username
    if form.validate_on_submit():
        comment = Comment(content = form.comment.data,user_id = current_user.id,pitch_id = pitch.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('main.comment',pitch_id=pitch_id))
    return render_template('comments.html', form = form,pitch=pitch,pitch_id=pitch_id,user=user)

app/templates/all_pitches.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% block styles%}
{{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}"> -->
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
{{super()}}
<div class="home text-center ">
    <h1>ALL PITCHES</h1>
    <nav aria-label="">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.pickup')}}">Pickup Lines</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.interview')}}">Interview</a>
</li>
<li class=" page-item">
                    <a class="page-link" href="{{url_for('main.promotion')}}">Promotion</a>
</li>
<li class=" page-item">
                        <a class="page-link" href="{{url_for('main.product')}}">Product</a>
</li>
</ul>
</nav>
{{macro.showPitch(general)}}
</div>
{% endblock %}
 

app/templates/base.html
<html>
{% block styles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
{% endblock %}

<body>
    {% block navbar %}
    {% include "navbar.html" %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block scripts %}
    {% endblock %}
</body>

</html>

app/templates/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
{% endblock %}

{% block content %}
<div class="container profile">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">


            <h2 class="text-center">Add Comment</h2>


            {{wtf.quick_form(form)}}

            <h1>Past Comments</h1>
            {% if comments %}
            {% for comment in comments%}


            <p>{{comment}}<small>Posted by: {{user}}</small></p>

            {% endfor %}
            {% else %}
            <p>No comments</p>
            {% endif %}


        </div>
        <div class="col-md-3"></div>

    </div>

</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block styles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Anonymous+Pro|Bungee+Inline|Italianno&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}

<h1>welcome to pitches.com where you pitch appreciated</h1>
<br>
<br>
<br>
<div class="para">
<a href="{{url_for('auth.login')}}" class='btn btn-primary'> start pitching</a>

</div>

{% endblock %}

app/templates/interview.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% block styles%}
{{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}"> -->
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
{{super()}}
<div class="home text-center ">
    <h1>Interview Pitches</h1>
    <nav aria-label="">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.pickup')}}">Pickup Lines</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.interview')}}">Interview</a>
</li>
<li class=" page-item">
                    <a class="page-link" href="{{url_for('main.promotion')}}">Promotion</a>
</li>
<li class=" page-item">
                        <a class="page-link" href="{{url_for('main.product')}}">Product</a>
</li>
</ul>
</nav>
<a type=" button" class="btn btn-secondary btn-sm" href="{{url_for('main.new_pitch')}}">Add a Pitch</a>
{{macro.showPitch(interview)}}
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
{% endblock %}
{{super()}}
<br>
<br>

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-8">
            
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            
            {{wtf.quick_form(login_form)}}
            <p> Don't have an account? <a href="{{url_for('auth.signup')}}"><button class="btn btn-primary">Sign up here</button> </a></p>
        </div>
        <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/macros.html
{% macro showPitch(pitches) %}
{% for pitch in pitches %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card mt-5">
                <div class="card-header">
                    <b>{{pitch.category}}</b>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <i><strong>{{pitch.title}}</strong></i><br>
                        <i>{{pitch.content}}</i>
                        <i>{{pitch.author}}</i>
                    </p>
                    <div>
                        <a href=""><button class="btn btn-danger">Up Vote</button></a>
                        <a href=""><button class="btb btn-primary">Down Vote</button>  </a>
                        <a href="{{url_for('main.comment',pitch_id=pitch.id)}}">Comment</a>
                    </div>
                </div>
                <li class="list-group-item">{{pitch.date_posted.strftime('%d-%m-%Y %H:%M')}}</li>
                <a href="{{url_for('main.new_pitch')}}" class="btn btn-small">Add a Pitch</a>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endmacro %}

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
{% endblock %}
{% block content %}
<div class="container new_pitch">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h2 class="text-center">Add a Pitch</h2>
            {{wtf.quick_form(pitch_form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/pickup.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}"> -->
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
{{super()}}
<div class="home text-center ">
    <h1>Pickup Pitches</h1>
    <nav aria-label="">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.pickup')}}">Pickup Lines</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.interview')}}">Interview</a>
</li>
<li class=" page-item">
                    <a class="page-link" href="{{url_for('main.promotion')}}">Promotion</a>
</li>
<li class=" page-item">
                        <a class="page-link" href="{{url_for('main.product')}}">Product</a>
</li>
</ul>
</nav>
<a type=" button" class="btn btn-secondary btn-sm" href="{{url_for('main.new_pitch')}}">Add a Pitch</a>
{{macro.showPitch(pickup)}}
</div>
{% endblock %}

app/templates/product.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}"> -->
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
{{super()}}
<div class="home text-center ">
    <h1>Product Pitches</h1>
    <nav aria-label="">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.pickup')}}">Pickup Lines</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.interview')}}">Interview</a>
            </li>
            <li class=" page-item">
                <a class="page-link" href="{{url_for('main.promotion')}}">Promotion</a>
            </li>
            <li class=" page-item">
                <a class="page-link" href="{{url_for('main.product')}}">Product</a>
            </li>
        </ul>
    </nav>
    <a type=" button" class="btn btn-secondary btn-sm" href="{{url_for('main.new_pitch')}}">Add a Pitch</a>
    {{macro.showPitch(product)}}
</div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html'%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
{% endblock %}
{% block content %}
{{super()}}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card profile-card mt-2">
                {% if user.profile_img %}
                <div class="card-img-block text-center">
                    <img class="card-img-top" src="{{url_for('static', filename = user.profile_img)}}"
                        alt="profile image" style="width:auto;height:30%;"
                        class="img-rounded img-responsive text-center">
                </div>
                {%else%}
                <div class="card-img-block">
                    <img class="card-img-top" src="{{url_for('static', filename = 'images/default.jpg')}}" alt=""
                        style="width:auto;height:30%;" class="img-rounded img-responsive text-center">
                </div>
                {%endif%}
                {% if user == current_user %}
                <form action="{{url_for('main.update_profile_pic',username=user.username)}}" method="post"
                    enctype="multipart/form-data" class="mt-2 text-center">
                    <h6><strong> Change Profile Picture</strong> </h6>
                    <input type="file" class="filestyle" data-icon="false" name="photo" required>
                    <input type="submit">
                </form>
                {% endif %}
                <div class="card-body text-center">
                    {% if user == current_user %}
                    <h5 class="card-title"><strong> {{current_user.username}}</strong><small> E-mail:
                            <strong>{{ current_user.email }} </strong></small></h5>
                    {%endif%}
                    {% if current_user.bio %}
                    <div class="bio">
                        <h6 class="card-title"> <strong>Your Bio</strong> </h6>
                        <p class="card-text ">{{ current_user.bio }}</p>
                    </div>
                    {% else %}
                    <div class="bio">
                        <h6 class="card-title"> <strong>Your Bio</strong> </h6>
                        <p class="card-text">It is really important to add Your bio .It helps other users on pitches to
                            know you more.</p>
                    </div>
                    {% endif %}
                    {% if user == current_user %}
                    <a href="{{url_for('main.update_profile',username=user.username)}}">Edit profile</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <h1 class='text-center' style="color:white;">Your Pitches</h1>
            {%if pitch%}
            {%for pitch_item in pitch%}
            <div class="container">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="card mt-5">
                            <div class="card-header">
                                <b>{{pitch_item.category}}</b>
                            </div>
                            <div class="card-body">
                                <p class="card-text">
                                    <i><strong>{{pitch_item.title}}</strong></i><br>
                                    <i>{{pitch_item.content}}</i>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
                {%endif%}
            </div>
        </div>
    </div>
    {% endblock %}

app/templates/promotion.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
{{super()}}
<div class="home text-center ">
    <h1>Promotion Pitches</h1>
    <nav aria-label="">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.pickup')}}">Pickup Lines</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url_for('main.interview')}}"">Interview</a>
</li>
<li class=" page-item">
                    <a class="page-link" href="{{url_for('main.promotion')}}"">Promotion</a>
</li>
<li class=" page-item">
                        <a class="page-link" href="{{url_for('main.product')}}"">Product</a>
</li>
</ul>
</nav>
<a type=" button" class="btn btn-secondary btn-sm" href="{{url_for('main.new_pitch')}}"">Add a Pitch</a>
{{macro.showPitch(promotion)}}
</div>
{% endblock %}

app/templates/sign_up.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
{{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}"> -->
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
<link href="https://fonts.googleapis.com/css?family=Italianno&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
{{super()}}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        
        <div class="col-md-6">
                
            <h1>SIGNUP</h1>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            {{wtf.quick_form(signup_form)}}
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

{% endblock %}

app/templates/update_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2 class="text-center">Update Your Bio</h2>
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}